/*!
* Auto-generated by FontAtlasGenerator.ts - DO NOT EDIT
* Copyright (C) 2026 Angel Cazacu - Licensed under the Mozilla Public License Version 2.0. See <https://www.mozilla.org/en-US/MPL/2.0/> for details.
*/

import { CharToGlyphs, Font } from "./font";

export enum Fonts
{
    Roboto_Regular,

}

export const FontsMap: Map<Fonts, Font> = new Map<Fonts, Font>();

export const Roboto_Regular: Font = new Font("Roboto_Regular", 1.175781, [
    { pixelW:1.027344, pixelH:1.175781, advance:1.025898 }, // �
    { pixelW:0.25, pixelH:1.175781, advance:0.248047 }, //  
    { pixelW:0.652344, pixelH:1.175781, advance:0.652344 }, // A
    { pixelW:0.625, pixelH:1.175781, advance:0.623047 }, // B
    { pixelW:0.652344, pixelH:1.175781, advance:0.650898 }, // C
    { pixelW:0.65625, pixelH:1.175781, advance:0.65625 }, // D
    { pixelW:0.570313, pixelH:1.175781, advance:0.568359 }, // E
    { pixelW:0.554688, pixelH:1.175781, advance:0.552734 }, // F
    { pixelW:0.683594, pixelH:1.175781, advance:0.681172 }, // G
    { pixelW:0.714844, pixelH:1.175781, advance:0.713398 }, // H
    { pixelW:0.273438, pixelH:1.175781, advance:0.271992 }, // I
    { pixelW:0.554688, pixelH:1.175781, advance:0.551758 }, // J
    { pixelW:0.628906, pixelH:1.175781, advance:0.627461 }, // K
    { pixelW:0.539063, pixelH:1.175781, advance:0.538594 }, // L
    { pixelW:0.875, pixelH:1.175781, advance:0.873047 }, // M
    { pixelW:0.714844, pixelH:1.175781, advance:0.713398 }, // N
    { pixelW:0.691406, pixelH:1.175781, advance:0.688008 }, // O
    { pixelW:0.632813, pixelH:1.175781, advance:0.630859 }, // P
    { pixelW:0.691406, pixelH:1.175781, advance:0.688008 }, // Q
    { pixelW:0.617188, pixelH:1.175781, advance:0.616211 }, // R
    { pixelW:0.59375, pixelH:1.175781, advance:0.59375 }, // S
    { pixelW:0.597656, pixelH:1.175781, advance:0.59668 }, // T
    { pixelW:0.648438, pixelH:1.175781, advance:0.648438 }, // U
    { pixelW:0.636719, pixelH:1.175781, advance:0.636719 }, // V
    { pixelW:0.890625, pixelH:1.175781, advance:0.887227 }, // W
    { pixelW:0.628906, pixelH:1.175781, advance:0.626953 }, // X
    { pixelW:0.601563, pixelH:1.175781, advance:0.600586 }, // Y
    { pixelW:0.601563, pixelH:1.175781, advance:0.599141 }, // Z
    { pixelW:0.546875, pixelH:1.175781, advance:0.543945 }, // a
    { pixelW:0.5625, pixelH:1.175781, advance:0.561523 }, // b
    { pixelW:0.523438, pixelH:1.175781, advance:0.523438 }, // c
    { pixelW:0.566406, pixelH:1.175781, advance:0.563984 }, // d
    { pixelW:0.53125, pixelH:1.175781, advance:0.530273 }, // e
    { pixelW:0.351563, pixelH:1.175781, advance:0.347656 }, // f
    { pixelW:0.5625, pixelH:1.175781, advance:0.561523 }, // g
    { pixelW:0.550781, pixelH:1.175781, advance:0.550781 }, // h
    { pixelW:0.246094, pixelH:1.175781, advance:0.243164 }, // i
    { pixelW:0.242188, pixelH:1.175781, advance:0.239258 }, // j
    { pixelW:0.507813, pixelH:1.175781, advance:0.506836 }, // k
    { pixelW:0.246094, pixelH:1.175781, advance:0.243164 }, // l
    { pixelW:0.878906, pixelH:1.175781, advance:0.876953 }, // m
    { pixelW:0.554688, pixelH:1.175781, advance:0.552266 }, // n
    { pixelW:0.570313, pixelH:1.175781, advance:0.570313 }, // o
    { pixelW:0.5625, pixelH:1.175781, advance:0.561523 }, // p
    { pixelW:0.570313, pixelH:1.175781, advance:0.568359 }, // q
    { pixelW:0.339844, pixelH:1.175781, advance:0.338867 }, // r
    { pixelW:0.519531, pixelH:1.175781, advance:0.516133 }, // s
    { pixelW:0.328125, pixelH:1.175781, advance:0.327148 }, // t
    { pixelW:0.554688, pixelH:1.175781, advance:0.551289 }, // u
    { pixelW:0.484375, pixelH:1.175781, advance:0.484375 }, // v
    { pixelW:0.753906, pixelH:1.175781, advance:0.751484 }, // w
    { pixelW:0.496094, pixelH:1.175781, advance:0.496094 }, // x
    { pixelW:0.476563, pixelH:1.175781, advance:0.473164 }, // y
    { pixelW:0.496094, pixelH:1.175781, advance:0.496094 }, // z
    { pixelW:0.257813, pixelH:1.175781, advance:0.257813 }, // !
    { pixelW:0.320313, pixelH:1.175781, advance:0.320313 }, // "
    { pixelW:0.898438, pixelH:1.175781, advance:0.897969 }, // @
    { pixelW:0.617188, pixelH:1.175781, advance:0.615742 }, // #
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // $
    { pixelW:0.734375, pixelH:1.175781, advance:0.732422 }, // %
    { pixelW:0.417969, pixelH:1.175781, advance:0.417969 }, // ^
    { pixelW:0.625, pixelH:1.175781, advance:0.62207 }, // &
    { pixelW:0.433594, pixelH:1.175781, advance:0.430664 }, // *
    { pixelW:0.339844, pixelH:1.175781, advance:0.338398 }, // }
    { pixelW:0.339844, pixelH:1.175781, advance:0.338398 }, // {
    { pixelW:0.453125, pixelH:1.175781, advance:0.451172 }, // _
    { pixelW:0.570313, pixelH:1.175781, advance:0.567383 }, // +
    { pixelW:0.277344, pixelH:1.175781, advance:0.276367 }, // -
    { pixelW:0.550781, pixelH:1.175781, advance:0.548828 }, // =
    { pixelW:0.199219, pixelH:1.175781, advance:0.196797 }, // ,
    { pixelW:0.265625, pixelH:1.175781, advance:0.263672 }, // .
    { pixelW:0.414063, pixelH:1.175781, advance:0.412617 }, // /
    { pixelW:0.472656, pixelH:1.175781, advance:0.472656 }, // ?
    { pixelW:0.242188, pixelH:1.175781, advance:0.242188 }, // :
    { pixelW:0.214844, pixelH:1.175781, advance:0.211445 }, // ;
    { pixelW:0.511719, pixelH:1.175781, advance:0.50832 }, // <
    { pixelW:0.523438, pixelH:1.175781, advance:0.522969 }, // >
    { pixelW:0.265625, pixelH:1.175781, advance:0.265156 }, // ]
    { pixelW:0.265625, pixelH:1.175781, advance:0.265156 }, // [
    { pixelW:0.34375, pixelH:1.175781, advance:0.342305 }, // (
    { pixelW:0.351563, pixelH:1.175781, advance:0.348164 }, // )
    { pixelW:0.3125, pixelH:1.175781, advance:0.309102 }, // `
    { pixelW:0.175781, pixelH:1.175781, advance:0.174805 }, // '
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 1
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 2
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 3
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 4
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 5
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 6
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 7
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 8
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 9
    { pixelW:0.5625, pixelH:1.175781, advance:0.562031 }, // 0

]);

FontsMap.set(Fonts.Roboto_Regular, Roboto_Regular);

CharToGlyphs.set(65533, 0);
CharToGlyphs.set(32, 1);
CharToGlyphs.set(65, 2);
CharToGlyphs.set(66, 3);
CharToGlyphs.set(67, 4);
CharToGlyphs.set(68, 5);
CharToGlyphs.set(69, 6);
CharToGlyphs.set(70, 7);
CharToGlyphs.set(71, 8);
CharToGlyphs.set(72, 9);
CharToGlyphs.set(73, 10);
CharToGlyphs.set(74, 11);
CharToGlyphs.set(75, 12);
CharToGlyphs.set(76, 13);
CharToGlyphs.set(77, 14);
CharToGlyphs.set(78, 15);
CharToGlyphs.set(79, 16);
CharToGlyphs.set(80, 17);
CharToGlyphs.set(81, 18);
CharToGlyphs.set(82, 19);
CharToGlyphs.set(83, 20);
CharToGlyphs.set(84, 21);
CharToGlyphs.set(85, 22);
CharToGlyphs.set(86, 23);
CharToGlyphs.set(87, 24);
CharToGlyphs.set(88, 25);
CharToGlyphs.set(89, 26);
CharToGlyphs.set(90, 27);
CharToGlyphs.set(97, 28);
CharToGlyphs.set(98, 29);
CharToGlyphs.set(99, 30);
CharToGlyphs.set(100, 31);
CharToGlyphs.set(101, 32);
CharToGlyphs.set(102, 33);
CharToGlyphs.set(103, 34);
CharToGlyphs.set(104, 35);
CharToGlyphs.set(105, 36);
CharToGlyphs.set(106, 37);
CharToGlyphs.set(107, 38);
CharToGlyphs.set(108, 39);
CharToGlyphs.set(109, 40);
CharToGlyphs.set(110, 41);
CharToGlyphs.set(111, 42);
CharToGlyphs.set(112, 43);
CharToGlyphs.set(113, 44);
CharToGlyphs.set(114, 45);
CharToGlyphs.set(115, 46);
CharToGlyphs.set(116, 47);
CharToGlyphs.set(117, 48);
CharToGlyphs.set(118, 49);
CharToGlyphs.set(119, 50);
CharToGlyphs.set(120, 51);
CharToGlyphs.set(121, 52);
CharToGlyphs.set(122, 53);
CharToGlyphs.set(33, 54);
CharToGlyphs.set(34, 55);
CharToGlyphs.set(64, 56);
CharToGlyphs.set(35, 57);
CharToGlyphs.set(36, 58);
CharToGlyphs.set(37, 59);
CharToGlyphs.set(94, 60);
CharToGlyphs.set(38, 61);
CharToGlyphs.set(42, 62);
CharToGlyphs.set(125, 63);
CharToGlyphs.set(123, 64);
CharToGlyphs.set(95, 65);
CharToGlyphs.set(43, 66);
CharToGlyphs.set(45, 67);
CharToGlyphs.set(61, 68);
CharToGlyphs.set(44, 69);
CharToGlyphs.set(46, 70);
CharToGlyphs.set(47, 71);
CharToGlyphs.set(63, 72);
CharToGlyphs.set(58, 73);
CharToGlyphs.set(59, 74);
CharToGlyphs.set(60, 75);
CharToGlyphs.set(62, 76);
CharToGlyphs.set(93, 77);
CharToGlyphs.set(91, 78);
CharToGlyphs.set(40, 79);
CharToGlyphs.set(41, 80);
CharToGlyphs.set(96, 81);
CharToGlyphs.set(39, 82);
CharToGlyphs.set(49, 83);
CharToGlyphs.set(50, 84);
CharToGlyphs.set(51, 85);
CharToGlyphs.set(52, 86);
CharToGlyphs.set(53, 87);
CharToGlyphs.set(54, 88);
CharToGlyphs.set(55, 89);
CharToGlyphs.set(56, 90);
CharToGlyphs.set(57, 91);
CharToGlyphs.set(48, 92);

